[package]
name = "ezmpc"
version = "0.1.0"
authors = ["kc1212 <kc1212@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4"
ff = { package = "ff_ce", version = "0.12", features = ["derive"] }
crossbeam-channel = "0.5"
quick-error = "2.0"

[dev-dependencies]
itertools = "0.9.0"