[package]
name = "ezmpc"
version = "0.1.0"
authors = ["kc1212 <kc1212@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4"
crossbeam-channel = "0.5"
thiserror = "1.0"
log = "0.4"
env_logger = "0.8"
alga = "0.9"
alga_derive = "0.9"
approx = "0.3"
num-traits = "0.2"
quickcheck = "0.9"
auto_ops = "0.1"
sha3 = "0.9"
cxx = "1.0"

[dev-dependencies]
itertools = "0.9.0"
test-env-log = "0.2"
quickcheck_macros = "0.9"

[build-dependencies]
cxx-build = "1.0"
